FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine AS base
WORKDIR /src
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine AS build

WORKDIR /src
COPY ["./nuget.config", "./nuget.config"]
COPY ["DDD.API/DDD.API.csproj", "DDD.API/"]
COPY ["DDD.Domain/DDD.Domain.csproj", "DDD.Domain/"]
COPY ["DDD.Infrastructure/DDD.Infrastructure.csproj", ".DDD.Infrastructure/"]
COPY ["DDD.Application/DDD.Application.csproj", "DDD.Application/"]
RUN dotnet restore "DDD.API/DDD.API.csproj"

COPY . .
WORKDIR "/src/DDD.API"
RUN dotnet build "DDD.API.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "DDD.API.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .

ENTRYPOINT ["dotnet", "DDD.API.dll"]